trigger:
  - master

resources:
  - repo: self

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'
  - task: CopyFiles@2
    inputs:
      Contents: 'build/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: CopyFiles@2
    inputs:
      Contents: 'server.js' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
  - task: CopyFiles@2
    inputs:
      Contents: 'api/**' # Pull the build directory (React)
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
  - task: CopyFiles@2
    inputs:
      SourceFolder: 'src'
      Contents: 'src/*.js'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/build'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build/'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
